# Generated by Django 3.1.3 on 2020-11-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanchonetes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(upload_to='assets/imagens/hamburguer1.jpg'),
        ),
    ]
