# Generated by Django 3.1.3 on 2020-11-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanchonetes', '0002_auto_20201129_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(upload_to='assets/imagens/'),
        ),
    ]
